[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "apache2-foreground"
healthCheckPath = "/"
healthCheckTimeout = 30

[variables]
PORT = "80"
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
